apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  database.yml: |
    production:
      adapter: postgresql
      database: <%= ENV['DB_NAME'] %>
      host: <%= ENV['DB_HOST'] %>
      port: <%= ENV['DB_PORT'] || '5432' %>
      username: <%= ENV['DB_USER'] %>
      password: <%= ENV['DB_PASSWORD'] %>
      encoding: utf8
